export const WIDTH_LAPTOP = 1279;
export const WIDTH_MOBILE = 768;

export const INITIAL_AMOUNT_MOVIES_LAPTOP = 12;
export const INITIAL_AMOUNT_MOVIES_TABLET = 8;
export const INITIAL_AMOUNT_MOVIES_MOBILE = 5;
export const ADD_AMOUNT_MOVIES_LAPTOP = 3;
export const ADD_AMOUNT_MOVIES_TABLET = 2;
export const ADD_AMOUNT_MOVIES_MOBILE = 2;

